var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-40151358-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

//Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    if($('div#table-of-contents').html() === undefined)
    {
      $("<div id=\"table-of-contents\"></div>").insertAfter("h1.title");
    }
    var c = 0;
    $('#click').click(function(){
      window.location.pathname = "./notes.html";
    });
    $('#gravatar').click(function() {
      c = c + 1;
      $("#click").text(c);
      $(".click-up").css({
        opacity: '100',
        top: '0px'
      });
      return $(".click-up").animate({
        top: '-100px',
        opacity: '0'
      }, "slow");
    });
  });
}).call(this);
